import Head from "next/head";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import Main from "../components/home/main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Donate</title>
        <meta name="description" content="Generated by kilros" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <Footer />
    </div>
  );
}
