import Head from "next/head";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import Main from "../components/home/main";

import { getDefaultWallets, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { chain, configureChains, createClient, WagmiConfig } from "wagmi";
import { jsonRpcProvider } from "wagmi/providers/jsonRpc";
import { publicProvider } from "wagmi/providers/public";
import { env } from "../constant";

export default function Home() {
  const { chains, provider } = configureChains(
    [chain.rinkeby],
    [jsonRpcProvider({ rpc: () => ({ http: env.RPC }) }), publicProvider()]
  );

  const { connectors } = getDefaultWallets({
    appName: "NFTKit Donate",
    chains,
  });

  const wagmiClient = createClient({
    autoConnect: true,
    connectors,
    provider,
  });
  return (
    <div>
      <WagmiConfig client={wagmiClient}>
        <RainbowKitProvider chains={chains}>
          <Head>
            <title>Donate</title>
            <meta name="description" content="Generated by kilros" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          <Main />
          <Footer />
        </RainbowKitProvider>
      </WagmiConfig>
    </div>
  );
}
